detection_validator:
  siem:
    type: "arcsight"  # arcsight, qradar, splunk
    api_endpoint: "https://arcsight.domain.com:8443"
    api_token: "YOUR_READ_TOKEN"
    verify_ssl: false
  timezone: "Europe/Warsaw"
  mapping:
    T1021: "Remote Desktop Protocol"
    T1078: "Valid Accounts"
    T1560: "Data Encrypted"
